// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network_api.proto

package projectannotations;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:projectannotations.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  java.lang.String getResponseData();
  com.google.protobuf.ByteString
      getResponseDataBytes();
}
