// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network_api.proto

package projectannotations;

public final class NetworkApi {
  private NetworkApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_projectannotations_RequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_projectannotations_RequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_projectannotations_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_projectannotations_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021network_api.proto\022\022projectannotations\"" +
      "&\n\016RequestMessage\022\024\n\014request_data\030\001 \001(\t\"" +
      "(\n\017ResponseMessage\022\025\n\rresponse_data\030\001 \001(" +
      "\t2g\n\nNetworkAPI\022Y\n\016ProcessRequest\022\".proj" +
      "ectannotations.RequestMessage\032#.projecta" +
      "nnotations.ResponseMessageB\026\n\022projectann" +
      "otationsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_projectannotations_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_projectannotations_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_projectannotations_RequestMessage_descriptor,
        new java.lang.String[] { "RequestData", });
    internal_static_projectannotations_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_projectannotations_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_projectannotations_ResponseMessage_descriptor,
        new java.lang.String[] { "ResponseData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
