// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network_api.proto

package projectannotations;

public interface RequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:projectannotations.RequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_data = 1;</code>
   * @return The requestData.
   */
  java.lang.String getRequestData();
  /**
   * <code>string request_data = 1;</code>
   * @return The bytes for requestData.
   */
  com.google.protobuf.ByteString
      getRequestDataBytes();
}
